In [2]:
import numpy as np

np.random.seed(16)

m = 10
n = 20
p = 0.2

x = np.random.rand(m, 2)
y = np.random.rand(n, 2)
Omega = np.random.rand(m, n) > p
Omega[0, 0] = False
A = (x @ y.T) * Omega

In [3]:
A

array([[0.        , 0.37342561, 0.        , 0.45223269, 0.5848406 ,
        0.36126553, 0.37028095, 0.34383474, 0.5085739 , 0.06480448,
        0.        , 0.        , 0.19755616, 0.1863894 , 0.33082705,
        0.        , 0.        , 0.47141881, 0.46486046, 0.64083187],
       [0.10841642, 0.33346782, 0.17520291, 0.43914664, 0.45853889,
        0.06985675, 0.06059047, 0.26549556, 0.        , 0.14553939,
        0.46197066, 0.        , 0.1981993 , 0.12177391, 0.54777822,
        0.        , 0.35017423, 0.43545713, 0.26369495, 0.57224625],
       [0.24832293, 0.30963204, 0.12311379, 0.39262155, 0.        ,
        0.17322236, 0.17204251, 0.2643305 , 0.39238157, 0.        ,
        0.46029395, 0.17931504, 0.        , 0.13222095, 0.        ,
        0.13267111, 0.27389309, 0.39812276, 0.30976426, 0.53134914],
       [0.23350656, 0.4674108 , 0.2237259 , 0.60717871, 0.        ,
        0.15775697, 0.        , 0.        , 0.56825808, 0.18324137,
        0.66483881, 0.19081269, 0.27265226, 0

In [4]:
Omega

array([[False,  True, False,  True,  True,  True,  True,  True,  True,
         True, False, False,  True,  True,  True, False, False,  True,
         True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True, False,  True,  True,  True, False,  True,  True,
         True,  True],
       [ True,  True,  True,  True, False,  True,  True,  True,  True,
        False,  True,  True, False,  True, False,  True,  True,  True,
         True,  True],
       [ True,  True,  True,  True, False,  True, False, False,  True,
         True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True],
       [ True,  True, False, False,  True,  True, False,  True,  True,
        False,  True, False,  True, False,  True,  True, False,  True,
         True,  True],
       [ True,  True,  True, False,  True,  True,  True,  True,  True,
        False,  True,  True,  True,  True, False,  True,  True,  True,
        False,  True],
       [ T

In [6]:
y

array([[0.12087875, 0.91768701],
       [0.56644633, 0.47201932],
       [0.31456642, 0.04321573],
       [0.75244492, 0.54326904],
       [0.76719043, 0.79044877],
       [0.07222138, 0.65971583],
       [0.05329934, 0.68502445],
       [0.44335096, 0.46799615],
       [0.66105933, 0.68996663],
       [0.26332948, 0.01147893],
       [0.77129445, 0.81614233],
       [0.1396416 , 0.57800675],
       [0.34067427, 0.23221549],
       [0.19864375, 0.27149077],
       [0.97685276, 0.21542898],
       [0.35640742, 0.01839995],
       [0.61679027, 0.23040539],
       [0.74235174, 0.58425021],
       [0.42010355, 0.70925283],
       [0.97204553, 0.81003912]])

In [7]:
A += np.ones((m,n)) - Omega

In [8]:
A

array([[1.        , 0.37342561, 1.        , 0.45223269, 0.5848406 ,
        0.36126553, 0.37028095, 0.34383474, 0.5085739 , 0.06480448,
        1.        , 1.        , 0.19755616, 0.1863894 , 0.33082705,
        1.        , 1.        , 0.47141881, 0.46486046, 0.64083187],
       [0.10841642, 0.33346782, 0.17520291, 0.43914664, 0.45853889,
        0.06985675, 0.06059047, 0.26549556, 1.        , 0.14553939,
        0.46197066, 1.        , 0.1981993 , 0.12177391, 0.54777822,
        1.        , 0.35017423, 0.43545713, 0.26369495, 0.57224625],
       [0.24832293, 0.30963204, 0.12311379, 0.39262155, 1.        ,
        0.17322236, 0.17204251, 0.2643305 , 0.39238157, 1.        ,
        0.46029395, 0.17931504, 1.        , 0.13222095, 1.        ,
        0.13267111, 0.27389309, 0.39812276, 0.30976426, 0.53134914],
       [0.23350656, 0.4674108 , 0.2237259 , 0.60717871, 1.        ,
        0.15775697, 1.        , 1.        , 0.56825808, 0.18324137,
        0.66483881, 0.19081269, 0.27265226, 0

In [9]:
import numpy as np
import cvxpy as cp

In [25]:
u = cp.Variable(m)
u = cp.reshape(u, (m,1))
v = cp.Variable(n)
v = cp.reshape(v, (n,1))
constraints = [ np.ones((1,m))*u == 0 ]
B = cp.exp(cp.abs(u*np.ones((1,n)) + np.ones((m,1))*v.T - cp.log(A)))
f = 0
for i in range(m):
  for j in range(n):
    f += Omega[i,j]*B[i,j]
obj = cp.Minimize(f)
prob = cp.Problem(obj, constraints)
prob.solve(solver = cp.SCS)

/usr/local/lib/python3.9/dist-packages/cvxpy/expressions/expression.py:612: UserWarning: 
This use of ``*`` has resulted in matrix multiplication.
Using ``*`` for matrix multiplication has been deprecated since CVXPY 1.1.
    Use ``*`` for matrix-scalar and vector-scalar multiplication.
    Use ``@`` for matrix-matrix and matrix-vector multiplication.
    Use ``multiply`` for elementwise multiplication.
This code path has been hit 22 times so far.

  warnings.warn(msg, UserWarning)
/usr/local/lib/python3.9/dist-packages/cvxpy/expressions/expression.py:612: UserWarning: 
This use of ``*`` has resulted in matrix multiplication.
Using ``*`` for matrix multiplication has been deprecated since CVXPY 1.1.
    Use ``*`` for matrix-scalar and vector-scalar multiplication.
    Use ``@`` for matrix-matrix and matrix-vector multiplication.
    Use ``multiply`` for elementwise multiplication.
This code path has been hit 23 times so far.

  warnings.warn(msg, UserWarning)
/usr/local/lib/python3.9/d

189.78342560819732

In [10]:
np.ones((1,n))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.]])

In [13]:
q = np.random.rand(m,1)
print(q)
q*np.ones((1,n))

[[0.46611697]
 [0.06845121]
 [0.10349704]
 [0.10135502]
 [0.32597413]
 [0.59350213]
 [0.80562884]
 [0.740684  ]
 [0.33278554]
 [0.07301441]]


array([[0.46611697, 0.46611697, 0.46611697, 0.46611697, 0.46611697,
        0.46611697, 0.46611697, 0.46611697, 0.46611697, 0.46611697,
        0.46611697, 0.46611697, 0.46611697, 0.46611697, 0.46611697,
        0.46611697, 0.46611697, 0.46611697, 0.46611697, 0.46611697],
       [0.06845121, 0.06845121, 0.06845121, 0.06845121, 0.06845121,
        0.06845121, 0.06845121, 0.06845121, 0.06845121, 0.06845121,
        0.06845121, 0.06845121, 0.06845121, 0.06845121, 0.06845121,
        0.06845121, 0.06845121, 0.06845121, 0.06845121, 0.06845121],
       [0.10349704, 0.10349704, 0.10349704, 0.10349704, 0.10349704,
        0.10349704, 0.10349704, 0.10349704, 0.10349704, 0.10349704,
        0.10349704, 0.10349704, 0.10349704, 0.10349704, 0.10349704,
        0.10349704, 0.10349704, 0.10349704, 0.10349704, 0.10349704],
       [0.10135502, 0.10135502, 0.10135502, 0.10135502, 0.10135502,
        0.10135502, 0.10135502, 0.10135502, 0.10135502, 0.10135502,
        0.10135502, 0.10135502, 0.10135502, 0

In [26]:
x_tilde = np.exp(u.value)
y_tilde = np.exp(v.value)
x = x/ np.sum(x_tilde)
y = np.sum(x_tilde)* y_tilde

In [36]:
rel_dev_opt = (prob.value - sum(sum(Omega))) / m / n
print('rel_dev_opt is %f' %rel_dev_opt)
A_11 = x[1]*y[1]

rel_dev_opt is 0.183917


In [35]:
A_11 = x[0,0] * y[0,0]
print('A_11 is %f' %A_11)

A_11 is 0.060149


In [38]:
print('value of x1 is %f' % x[0,0])
print('value of y1 is %f' % y[0,0])

value of x1 is 0.021658
value of y1 is 2.777167
