Import dependencie

In [42]:
import numpy as np
from scipy.sparse import random as sprand

Data

In [43]:
m=20
n=10
p=8
np.random.seed(2)
R = np.round(np.random.rand(m, n))
A = sprand(p, m, density=0.2).toarray()
c = 10*np.random.rand(m) + 20
b = 20*np.random.rand(p) + 30

Solve the problem for interference constrained problem

In [44]:
import cvxpy as cp
f = cp.Variable((n,1))
obj = cp.Maximize(cp.sum(cp.vstack(cp.sqrt(f))))
constraints = [R@f <= c.reshape((m,1)),
               A@(R@f) <= b.reshape((p,1))]

problem = cp.Problem(obj, constraints)
result = problem.solve()

optimal f values

In [45]:
print('optimal f is:')
print(f.value)

optimal f is:
[[0.74703043]
 [5.21609215]
 [4.3697859 ]
 [2.12366526]
 [1.23994469]
 [0.87671337]
 [5.91987917]
 [6.94814676]
 [0.8608359 ]
 [4.48192142]]


utility of each flow and sum of all utilities

In [46]:
print('utility of each route are:')
print(cp.sqrt(f).value)
print('sum of all utilities is:')
print(cp.sum(cp.vstack(cp.sqrt(f))).value)

utility of each route are:
[[0.86430922]
 [2.28387656]
 [2.09040329]
 [1.45728009]
 [1.11352804]
 [0.93632974]
 [2.43308018]
 [2.63593376]
 [0.92781243]
 [2.11705489]]
sum of all utilities is:
16.859608189260747


links that use almost all of the capacity for the firs problem

In [47]:
print('links that use almost all of the capacity are:')
print(c.reshape((m,1)) - R@(f.value) <= 0.001)

links that use almost all of the capacity are:
[[False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [ True]]


Solve the problem for the case that we do not have any constraint for interference

In [48]:
import cvxpy as cp
f = cp.Variable((n,1))
obj = cp.Maximize(cp.sum(cp.vstack(cp.sqrt(f))))
constraints = [R@f <= c.reshape((m,1))
               ]

problem = cp.Problem(obj, constraints)
result = problem.solve()
print('optimal f is:')
f.value

optimal f is:


array([[1.8450443 ],
       [3.0464918 ],
       [5.05091504],
       [8.68636942],
       [4.94266877],
       [3.72744287],
       [7.45300289],
       [2.47187847],
       [1.68691061],
       [4.81984826]])

utility function of the second case(and sum of them)

In [49]:
print('utility of each route are:')
print(cp.sqrt(f).value)
print('sum of all utilities is:')
print(cp.sum(cp.vstack(cp.sqrt(f))).value)

utility of each route are:
[[1.35832408]
 [1.74542024]
 [2.24742409]
 [2.94726474]
 [2.22321136]
 [1.93065866]
 [2.73001884]
 [1.57222087]
 [1.29881123]
 [2.19541528]]
sum of all utilities is:
20.248769393794312


links that use almost all of the capacity for the second problem

In [50]:
print('links that use almost all of the capacity are:')
print(c.reshape((m,1)) - R@(f.value) <= 0.001)

links that use almost all of the capacity are:
[[False]
 [ True]
 [False]
 [False]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [ True]
 [ True]
 [False]
 [False]
 [False]
 [False]
 [False]
 [ True]
 [False]
 [ True]]
